version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@3.1.0
jobs:
  deploy-vpn:
    machine: true
    steps:
      - checkout
      - aws-ecr/ecr-login
      - run:
          name: 'pull image'
          command: docker pull 661123053817.dkr.ecr.eu-central-1.amazonaws.com/procom-node-vpn:latest | egrep -v "^[[:space:]]*$|^#"
      - run:
          name: 'start container'
          command: |
            set -e
            docker run --cap-add=NET_ADMIN \
              -e "CI=$CI" \
              -e "CIRCLE_BRANCH=$CIRCLE_BRANCH" \
              -e "AWS_ACCESS_KEY=$AWS_ACCESS_KEY" \
              -e "AWS_SECRET_KEY=$AWS_SECRET_KEY" \
              -v /dev/net:/dev/net \
              -v "$(pwd)"/../project:/home/circleci/project \
              --name node-vpn \
              661123053817.dkr.ecr.eu-central-1.amazonaws.com/procom-node-vpn:latest \
              curl 192.168.2.41:8080
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-vpn
